name: Build and Deploy to Azure

on:
  workflow_dispatch:

env:
  BACKUP_PATH: /home/ankit/github-action-testing/backup
  SITE_PATH:  /home/ankit/github-action-testing/sites
  AZUREDEPLOY_PATH:  /home/ankit/github-action-testing/azuredeploy

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      # Step 1️⃣ Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2️⃣ Build and store artifact
      - name: Build Project
        run: |
          echo "Building project..."
          mkdir build_output
          echo "Sample build file" > build_output/app.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: build_output/

      # # Step 3️⃣ Login to Azure
      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: |
      #       {
      #         "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
      #         "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
      #         "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
      #         "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
      #       }

      # Step 4️⃣ Get GitHub Runner Public IP
      - name: Get Runner Public IP
        id: get_ip
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "Public IP: $IP"
          echo "ip=$IP" >> $GITHUB_OUTPUT

      # Step 5️⃣ Add IP to Azure NSG
      # - name: Whitelist Runner IP in NSG
      #   run: |
      #     az network nsg rule create \
      #       --resource-group ${{ secrets.NSG_RESOURCE_GROUP }} \
      #       --nsg-name ${{ secrets.NSG_NAME }} \
      #       --name GitHubRunnerRule \
      #       --priority 100 \
      #       --source-address-prefixes ${{ steps.get_ip.outputs.ip }} \
      #       --destination-port-ranges 22 \
      #       --access Allow \
      #       --protocol Tcp \
      #       --description "Temporary rule for GitHub Actions Runner"

      # Step 6️⃣ Backup Sites folder
      - name: Backup Sites folder
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          mkdir -p $BACKUP_PATH/main/$TIMESTAMP
          cp -r $SITE_PATH/* $BACKUP_PATH/main/$TIMESTAMP/ || echo "No sites to backup"

      # Step 7️⃣ Git pull and backup change folder
      - name: Git Pull AzureDeploy
        run: |
          cd $AZUREDEPLOY_PATH
          git pull origin main
          cd ..
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          mkdir -p $BACKUP_PATH/change/$TIMESTAMP
          cp -r $AZUREDEPLOY_PATH/* $BACKUP_PATH/change/$TIMESTAMP/

      # Step 8️⃣ Replace latest file into sites folder
      - name: Copy Latest Files to Sites
        run: |
          LATEST_FOLDER=$(ls -td $BACKUP_PATH/change/* | head -1)
          cp -r $LATEST_FOLDER/* $SITE_PATH/

      # # Step 9️⃣ Remove IP from Azure NSG
      # - name: Remove Runner IP from NSG
      #   if: always()
      #   run: |
      #     az network nsg rule delete \
      #       --resource-group ${{ secrets.NSG_RESOURCE_GROUP }} \
      #       --nsg-name ${{ secrets.NSG_NAME }} \
      #       --name GitHubRunnerRule
